### ISSUE TITLE
on-page menu not visible if DOI is given

### ISSUE THREAD

**Issue by corihart** [greenmeen/zotero-roam#10] opened 2021-08-08 09:50 UTC
First off, thanks for this amazing plug-in you created to bring Zotero data into Roam!

My issue is with the on-page menu. 
I'd only ever seen it displayed properly for one of my sources, which was an unpublished manuscript.
Now I have found out that, for me,  if a source has a DOI in Zotero, only the DOI will be displayed on its Roam page, none of those buttons for Google Scholar, Connected Papers etc.

before

![image](https://user-images.githubusercontent.com/42076400/128627858-91cb4b75-ebf5-40bb-9bf5-7565ed0db87b.png)

vs after DOI removed and zoteroRoam reloaded

![image](https://user-images.githubusercontent.com/42076400/128627924-62b19333-11d8-499b-b869-580d8b56329d.png)

**Comment by greenmeen** [comment] 2021-08-08 11:35
Hi there! Looks like there some error going on while rendering the on-page menu in the first screenshot, which isn't caught & so the menu rendering doesn't complete.
Since it loads without issue when there's no DOI, I think the issue is in the citations data retrieval.

Are you able to put the DOI back in, reload your Roam page, and send me a screenshot of the browser console output?
There should be errors there that point to the underlying problem. Let me know if you need help with that :)

(the console is part of the Developer Tools of the browser ; usually Ctrl-Shift-I opens up the dev tools, then you can go to the "Console" tab ; you can also find the dev tools through your browser menu, typically under "Advanced" or similar ; or you can right-click in a non-interactive spot on the page, then click "Inspect")

**Comment by corihart** [comment] 2021-08-08 16:10
Here is the console and the error it displays:

![image](https://user-images.githubusercontent.com/42076400/128638325-d395d837-b3fd-4a55-bc75-4084b56cadab.png)

**Comment by greenmeen** [comment] 2021-08-08 16:32
Thanks so much! I located the bug, starting on a fix - will be up by end of today, or tomorrow at the latest.

**Comment by greenmeen** [comment] 2021-08-09 03:29
This should be fixed in the just-published version (0.6.65). There was an issue where, if any library item had a DOI but in the wrong format, the code would fail when generating the on-page menu.
Feel free to open this back up if you still run into issues!

**Closed by greenmeen** 2021-08-09 03:30 UTC

**Comment by corihart** [comment] 2021-08-09 07:36
Awesome, thank you so much!

I can confirm that it works for me now (after figuring out I need to update):
![image](https://user-images.githubusercontent.com/42076400/128672954-8f1f8b7b-8c26-49ce-a1da-4c7e621fd0eb.png)
